# Generated by Django 3.0.7 on 2020-06-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workteam_activity',
            unique_together={('workteam', 'activity')},
        ),
    ]
