# Generated by Django 3.0.7 on 2020-06-18 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20200618_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cal.Grade'),
        ),
    ]
